### ISSUE TITLE
New lending page has a strange Horizontal scroll menu

### ISSUE THREAD

**Issue by bitcoinuser** [DistributedCollective/Sovryn-frontend#1407]
Hi,

New lending page has a strange Horizontal scroll menu.

![Captura de tela de 2021-06-30 11-31-21](https://user-images.githubusercontent.com/1178856/123979033-bd594c80-d996-11eb-8c50-016d34cae64e.png)

**Comment by soulBit** [comment]
Closing this as issue should be resolved in latest version

**Comment by bitcoinuser** [comment]
Where can I test?

**Comment by bitcoinuser** [comment]
I loaded this https://github.com/DistributedCollective/Sovryn-frontend/pull/1395 and I still reproduce the problem.

**Comment by bitcoinuser** [comment]
Same problem @soulBit. Please reopen.

**Comment by soulBit** [comment]
@bitcoinuser could you provide some details to replicate this:

- Link you are seeing the issue on
- Screenshot of the issue
- Screen/browser width

**Comment by bitcoinuser** [comment]
> @bitcoinuser could you provide some details to replicate this:
> 
> * Link you are seeing the issue on
> * Screenshot of the issue
> * Screen/browser width

Hi,

My monitor resolution is: 1366 x 768 (16:9)
Browser: Brave on Linux with zoom 100%.
Obs. I think in my case the pie chart should be removed, so will resolve the problem.

**Comment by bitcoinuser** [comment]
Hi, any news on this? Thanks

**Comment by bitcoinuser** [comment]
Fixed on test.sovryn.app.
